#!/bin/sh
# echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
# echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
# echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
docker run -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" -p 8000:8000 -p 8443:8443 cookie
